/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peaceprivate;

import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import com.mysql.jdbc.Statement;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import peaceprivate.Login;
/**
 *
 * @author Ismail
 */
public class MainHomePage extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

Login l;
    /**
     * Creates new form MainHomePage
     * @param Image
     * @param name
     * @param position
     */
    public MainHomePage(byte [] Image,String name, String position) {
        initComponents();
       conn=javaconnect.ConnecrDb();
      // retreve();
       Name_of_the_active_user.setText(String.valueOf(Emp.empId).toString());
       byte[] image=Image;
       ImageIcon icon=new ImageIcon(image);
       Label_for_User_Image.setIcon(ResizedImage(image));
       Name_of_the_active_user.setText(name);
       position_of_the_active_user.setText(position);
       txt_emp.setText(String.valueOf(Emp.empId).toString());
     
       
       
           new Thread(){
            
            public void run(){
                while(true){
                    Date dNow = new Date( );
                    
                    SimpleDateFormat ft = new SimpleDateFormat ("E yyyy.MM.dd hh:mm:ss a");
                    String time = ""+ft.format(dNow);
                    
                    time_Label.setText(time);
                    
                }
            }
            
        }.start();
           
           
           
        
        //Focus for ID TextField
        search.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                //To change body of generated methods, choose Tools | Templates.
                if(search.getText().equalsIgnoreCase("Search Student ....")){
                    search.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if(search.getText().equalsIgnoreCase("")){
                    search.setText("Search Student ....");
                } //To change body of generated methods, choose Tools | Templates.
            }
        });
           
           
           
           
           
    }
public void retreve(){
        DefaultTableModel dm = getData();
        
        jTable1.setModel(dm);
        
    }
   
 public ImageIcon ResizedImage(byte [] path){
        
        ImageIcon image1=new ImageIcon(path);
        Image img=image1.getImage();
        Image scaledImage=img.getScaledInstance(Label_for_User_Image.getWidth(), Label_for_User_Image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon Imagedone=new ImageIcon(scaledImage);
     return Imagedone;
 }
  public void showDeposited(){
        try{

            String sql ="select SUM(pay) from register";

            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
           if(rs.next()){
                String add2 =rs.getString("SUM(pay)");
                TotalMoney.setText(add2);
           }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
        }
  }
 
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccInfo_Panel = new javax.swing.JPanel();
        Label_for_User_Image = new javax.swing.JLabel();
        Name_of_the_active_user = new javax.swing.JLabel();
        position_of_the_active_user = new javax.swing.JLabel();
        txt_emp = new javax.swing.JLabel();
        Panel_Reg = new javax.swing.JPanel();
        Inside_PanelReg = new javax.swing.JPanel();
        RegStudent = new javax.swing.JButton();
        paymentButtonHome = new javax.swing.JButton();
        Generate_btn_in_Report = new javax.swing.JButton();
        Admin_Home = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Settings_Panel = new javax.swing.JPanel();
        Inside_Settings = new javax.swing.JPanel();
        profileButton = new javax.swing.JButton();
        auditButton = new javax.swing.JButton();
        backupButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        MainPanel = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        time_Label = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        totalPopulation = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Print_btn_in_Report = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TotalMoney = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        AccInfo_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.pink), "Account Info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        javax.swing.GroupLayout AccInfo_PanelLayout = new javax.swing.GroupLayout(AccInfo_Panel);
        AccInfo_Panel.setLayout(AccInfo_PanelLayout);
        AccInfo_PanelLayout.setHorizontalGroup(
            AccInfo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccInfo_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_for_User_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccInfo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name_of_the_active_user, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(position_of_the_active_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AccInfo_PanelLayout.createSequentialGroup()
                        .addComponent(txt_emp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        AccInfo_PanelLayout.setVerticalGroup(
            AccInfo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_for_User_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AccInfo_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Name_of_the_active_user, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(position_of_the_active_user, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Panel_Reg.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true), null));

        Inside_PanelReg.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 12)), new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true))); // NOI18N

        RegStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peaceprivate/images/icons8_add_user_male_32.png"))); // NOI18N
        RegStudent.setMnemonic('R');
        RegStudent.setText("Register");
        RegStudent.setToolTipText("Click To Register Student Or Press R");
        RegStudent.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true)));
        RegStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegStudentActionPerformed(evt);
            }
        });

        paymentButtonHome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        paymentButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peaceprivate/images/icons8_payment_history_32.png"))); // NOI18N
        paymentButtonHome.setMnemonic('p');
        paymentButtonHome.setText("Payment");
        paymentButtonHome.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true)));
        paymentButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonHomeActionPerformed(evt);
            }
        });

        Generate_btn_in_Report.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Generate_btn_in_Report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peaceprivate/images/icons8_report_file_32.png"))); // NOI18N
        Generate_btn_in_Report.setMnemonic('e');
        Generate_btn_in_Report.setText("Report");
        Generate_btn_in_Report.setToolTipText("");
        Generate_btn_in_Report.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true)));
        Generate_btn_in_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generate_btn_in_ReportActionPerformed(evt);
            }
        });

        Admin_Home.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Admin_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peaceprivate/images/user_24px.png"))); // NOI18N
        Admin_Home.setText("Manage User");
        Admin_Home.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true)));
        Admin_Home.setMaximumSize(new java.awt.Dimension(83, 37));
        Admin_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Inside_PanelRegLayout = new javax.swing.GroupLayout(Inside_PanelReg);
        Inside_PanelReg.setLayout(Inside_PanelRegLayout);
        Inside_PanelRegLayout.setHorizontalGroup(
            Inside_PanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inside_PanelRegLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Inside_PanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Inside_PanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Generate_btn_in_Report, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paymentButtonHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(RegStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Admin_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        Inside_PanelRegLayout.setVerticalGroup(
            Inside_PanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inside_PanelRegLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(RegStudent)
                .addGap(18, 18, 18)
                .addComponent(paymentButtonHome)
                .addGap(18, 18, 18)
                .addComponent(Generate_btn_in_Report)
                .addGap(18, 18, 18)
                .addComponent(Admin_Home, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Panel_RegLayout = new javax.swing.GroupLayout(Panel_Reg);
        Panel_Reg.setLayout(Panel_RegLayout);
        Panel_RegLayout.setHorizontalGroup(
            Panel_RegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RegLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Inside_PanelReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_RegLayout.setVerticalGroup(
            Panel_RegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RegLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Inside_PanelReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Settings_Panel.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true), null));

        Inside_Settings.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Settings", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 12)), new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 1, true))); // NOI18N

        profileButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        profileButton.setText("Manage Database");
        profileButton.setToolTipText("");
        profileButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true)));
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        auditButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        auditButton.setText("Audit");
        auditButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true)));
        auditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditButtonActionPerformed(evt);
            }
        });

        backupButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        backupButton.setText("Backup/Restore");
        backupButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true)));
        backupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupButtonActionPerformed(evt);
            }
        });

        aboutButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        aboutButton.setText("About");
        aboutButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true)));
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Inside_SettingsLayout = new javax.swing.GroupLayout(Inside_Settings);
        Inside_Settings.setLayout(Inside_SettingsLayout);
        Inside_SettingsLayout.setHorizontalGroup(
            Inside_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inside_SettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Inside_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(auditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backupButton, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(aboutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Inside_SettingsLayout.setVerticalGroup(
            Inside_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inside_SettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileButton)
                .addGap(18, 18, 18)
                .addComponent(auditButton)
                .addGap(18, 18, 18)
                .addComponent(backupButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(aboutButton))
        );

        javax.swing.GroupLayout Settings_PanelLayout = new javax.swing.GroupLayout(Settings_Panel);
        Settings_Panel.setLayout(Settings_PanelLayout);
        Settings_PanelLayout.setHorizontalGroup(
            Settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Settings_PanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Inside_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        Settings_PanelLayout.setVerticalGroup(
            Settings_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Settings_PanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(Inside_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSeparator4.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(255, 0, 0));

        Logout.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peaceprivate/images/icons8_shutdown_32.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peaceprivate/images/icons8_search_filled_32.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        search.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search.setText("Search Student ....");
        search.setToolTipText("Note!! Search By ID Number");
        search.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.orange, java.awt.Color.pink)));
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        search.setDropMode(javax.swing.DropMode.INSERT);

        jScrollPane1.setViewportView(jTable1);

        totalPopulation.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peaceprivate/images/icons8_student_16.png"))); // NOI18N
        jLabel2.setText("No Of Students");

        Print_btn_in_Report.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Print_btn_in_Report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peaceprivate/images/icons8_print_16.png"))); // NOI18N
        Print_btn_in_Report.setText("Print");
        Print_btn_in_Report.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true)));
        Print_btn_in_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_btn_in_ReportActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peaceprivate/images/icons8_paid_16.png"))); // NOI18N
        jButton1.setText("Show Total");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TotalMoney.setEditable(false);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(totalPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Print_btn_in_Report, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(time_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(Print_btn_in_Report)
                            .addComponent(jButton1))
                        .addGap(15, 15, 15))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(time_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AccInfo_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Settings_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Panel_Reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator3)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AccInfo_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel_Reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Settings_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("Peace English Private School");
        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegStudentActionPerformed
        // TODO add your handling code here:
        new Register().setVisible(true);
    }//GEN-LAST:event_RegStudentActionPerformed

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void paymentButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonHomeActionPerformed
        // TODO add your handling code here:
        new Payment().setVisible(true);
    }//GEN-LAST:event_paymentButtonHomeActionPerformed

    private void Generate_btn_in_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generate_btn_in_ReportActionPerformed
        // TODO add your handling code here:
                       int z=0;
for(int y=0; y< jTable1.getRowCount(); y++){

z+=Integer.parseInt(jTable1.getValueAt(y,5).toString());

}
totalPopulation.setText(z+"   Students");
 retreve();
    }//GEN-LAST:event_Generate_btn_in_ReportActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        // TODO add your handling code here:
        new Profile().setVisible(true);
    }//GEN-LAST:event_profileButtonActionPerformed

    private void auditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditButtonActionPerformed
        // TODO add your handling code here:
        new Audit().setVisible(true);
    }//GEN-LAST:event_auditButtonActionPerformed

    private void backupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupButtonActionPerformed
        // TODO add your handling code here:
        new Backup().setVisible(true);
    }//GEN-LAST:event_backupButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void Admin_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_HomeActionPerformed
        // TODO add your handling code here:
        new Admin_home().setVisible(true);
    }//GEN-LAST:event_Admin_HomeActionPerformed

    private void Print_btn_in_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_btn_in_ReportActionPerformed
        // TODO add your handling code here:
          String t_pop = totalPopulation.getText();
        String emp = position_of_the_active_user.getText().toString();
        
        
          JFileChooser dialog = new JFileChooser();
            dialog.setSelectedFile(new File("Facility Students Report.pdf"));
            int dialogResult = dialog.showSaveDialog(null);
            if (dialogResult==JFileChooser.APPROVE_OPTION){
            String filePath = dialog.getSelectedFile().getPath();
           
        try {
            // TODO add your handling code here:
            
            String sql ="select * from `register`";
            
 
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
           
           Document myDocument = new Document();
           PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath ));
           PdfPTable table = new PdfPTable(11);
           myDocument.open();
           
   
           float[] columnWidths = new float[] { 3,9,9,9,9,9,9,9,9,9,9};
           table.setWidths(columnWidths);

           table.setWidthPercentage(100); //set table width to 100%
           
           myDocument.add(new Paragraph("Peace Institute Of Spoken English & Writing Skills",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD )));
           myDocument.add(new Paragraph("Facility Students Report",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD )));
           myDocument.add(new Paragraph(new Date().toString()));
           myDocument.add(new Paragraph("Report Generated By  Employe ID:- "+emp,FontFactory.getFont(FontFactory.TIMES_BOLD,14,Font.BOLD)));
           myDocument.add(new Paragraph("-----------------------------------------------------------------------------"));
          table.addCell(new PdfPCell(new Paragraph("ID",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("Full Name",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("Date",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("Branch",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("Status",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("Class No",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("Class Time",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("Mobile Number",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("Check Payment",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("Courses",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
          table.addCell(new PdfPCell(new Paragraph("Amount Of Payment",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
       
          
     
          
          
          while(rs.next())
            {
           table.addCell(new PdfPCell(new Paragraph(rs.getString(1),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(2),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(3),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(4),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(6),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(7),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(8),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(9),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(11),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(12),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
           table.addCell(new PdfPCell(new Paragraph(rs.getString(13),FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.PLAIN))));
            }
           
           myDocument.add(table);
           myDocument.add(new Paragraph("--------------------------------------------------------------------------------------------"));
           myDocument.add(new Paragraph("Total Students      :"+t_pop,FontFactory.getFont(FontFactory.TIMES_BOLD,12,Font.BOLD )));
           myDocument.close();  
           JOptionPane.showMessageDialog(null,"Report was successfully generated");
            
     }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
         
         
     }
     finally {
            
            try{
                rs.close();
                pst.close();
                
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
         
            }
     }
        Date currentDate = GregorianCalendar.getInstance().getTime();
            DateFormat df = DateFormat.getDateInstance();
            String dateString = df.format(currentDate);

            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
            String timeString = sdf.format(d);

            String val0 = timeString;
            String val1 = dateString;
            String val = txt_emp.getText().toString();
                try{

                String reg= "insert into Audit (emp_id, date, status) values ('"+val+"','"+val0+" / "+val1+"','Generate Facility Report')";
                pst=conn.prepareStatement(reg);
                pst.execute();

                  }
            catch (Exception e)

            {
                JOptionPane.showMessageDialog(null,e);
            }
        
   }
    }//GEN-LAST:event_Print_btn_in_ReportActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        try{

            String sql ="select * from `register` where idnum=? ";

            pst=conn.prepareStatement(sql);
            pst.setString(1,search.getText());
            
            rs=pst.executeQuery();
            retreve();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
               
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Button to show the total money of the student
        
        showDeposited();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           /* for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            } */
           UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                //new MainHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccInfo_Panel;
    public javax.swing.JButton Admin_Home;
    public javax.swing.JButton Generate_btn_in_Report;
    private javax.swing.JPanel Inside_PanelReg;
    private javax.swing.JPanel Inside_Settings;
    private javax.swing.JLabel Label_for_User_Image;
    private javax.swing.JLabel Logout;
    private javax.swing.JPanel MainPanel;
    public javax.swing.JLabel Name_of_the_active_user;
    private javax.swing.JPanel Panel_Reg;
    public javax.swing.JButton Print_btn_in_Report;
    public javax.swing.JButton RegStudent;
    private javax.swing.JPanel Settings_Panel;
    private javax.swing.JTextField TotalMoney;
    public javax.swing.JButton aboutButton;
    public javax.swing.JButton auditButton;
    public javax.swing.JButton backupButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTable jTable1;
    public javax.swing.JButton paymentButtonHome;
    public javax.swing.JLabel position_of_the_active_user;
    public javax.swing.JButton profileButton;
    private javax.swing.JTextField search;
    private javax.swing.JLabel time_Label;
    public javax.swing.JTextField totalPopulation;
    private javax.swing.JLabel txt_emp;
    // End of variables declaration//GEN-END:variables
byte [] forImage=null;
ImageIcon format=null;


private DefaultTableModel getData() {
        String conString ="jdbc:mysql://localhost:3306/peace";
        String username ="root";
        String passward ="";
        
        DefaultTableModel dm = new DefaultTableModel();
        dm.addColumn("ID Number");
        dm.addColumn("Full Name");
        dm.addColumn("Date");
        dm.addColumn("Branch");
        dm.addColumn("Status");
        dm.addColumn("Class No");
        dm.addColumn("Class Time");
        dm.addColumn("Mobile No");
        dm.addColumn("Check Payment");
        dm.addColumn("Courses");
        dm.addColumn("Amount Of Payment");
        
        
        String sql = "select `idnum`,`name`,`month`,`branch`,`status`,`classnum`,`ctype`,`mobnum`,`payCheck`,`courses`,`pay` from `register` ";
        
        try{
            com.mysql.jdbc.Connection con= (com.mysql.jdbc.Connection) DriverManager.getConnection(conString, username, passward);
            
            Statement s =(Statement) con.prepareStatement(sql);
            
            ResultSet rs =s.executeQuery(sql);
            
            while(rs.next()){
                String id = rs.getString(1);
                String fname = rs.getString(2);
                String sx = rs.getString(3);
                String hnum = rs.getString(4);
                String sttus = rs.getString(5);
                String cnum = rs.getString(6);
                String ctyp = rs.getString(7);
                String mno = rs.getString(8);
                String pchk = rs.getString(9);
                String courses = rs.getString(10);
                String pay = rs.getString(11);
                
                
                
                dm.addRow(new String[]{id,fname,sx,hnum,sttus,cnum,ctyp,mno,pchk,courses,pay});
                
            }
            
            return dm;
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
        return null;
    }



}
